// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEeiG3bJeKOL-26hKcB20pyNftPLtKxb4',
    appId: '1:168013637677:web:c26417330c04f14b2270a4',
    messagingSenderId: '168013637677',
    projectId: 'habitflow-app-8d058',
    authDomain: 'habitflow-app-8d058.firebaseapp.com',
    storageBucket: 'habitflow-app-8d058.firebasestorage.app',
    measurementId: 'G-18FSL7SXD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB311QRkpQJXyt2Vvk8gjQ3oo5z7ZLsteQ',
    appId: '1:168013637677:android:da354b68328a1d982270a4',
    messagingSenderId: '168013637677',
    projectId: 'habitflow-app-8d058',
    storageBucket: 'habitflow-app-8d058.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrJIlsm_ZGR74OFDILWaM4N9ZHHokc5aw',
    appId: '1:168013637677:ios:df7a82c6681b45c32270a4',
    messagingSenderId: '168013637677',
    projectId: 'habitflow-app-8d058',
    storageBucket: 'habitflow-app-8d058.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrJIlsm_ZGR74OFDILWaM4N9ZHHokc5aw',
    appId: '1:168013637677:ios:df7a82c6681b45c32270a4',
    messagingSenderId: '168013637677',
    projectId: 'habitflow-app-8d058',
    storageBucket: 'habitflow-app-8d058.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEeiG3bJeKOL-26hKcB20pyNftPLtKxb4',
    appId: '1:168013637677:web:7b6c779fa330fb8b2270a4',
    messagingSenderId: '168013637677',
    projectId: 'habitflow-app-8d058',
    authDomain: 'habitflow-app-8d058.firebaseapp.com',
    storageBucket: 'habitflow-app-8d058.firebasestorage.app',
    measurementId: 'G-ER21FPKX8S',
  );

}